databases:
  - name: hotel_booking_project
    databaseName: hotel_booking_project
    user: hotel_booking_project

services:
  - type: web
    name: hotel-booking-project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn hotel_booking_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel_booking_project
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
